config/routes.rb
Rails.application.routes.draw do
mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  resources :documents
  resources :events
  resources :members
    devise_for :users, :controllers => { registrations: 'registrations' }

    get 'pages/index'
	get 'about' => 'pages#about'

	root 'pages#index'

	match "*path", to: redirect('/'), via: :all

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Antietam Distance Company</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato">
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <nav class="navbar fixed-top navbar-expand navbar-dark bg-dark">
            <a class="navbar-brand" href="<%= root_path %>" style="padding:0;margin:0;">
                <img src="/assets/248SQ.png" width="80" height="80" class="d-inline-block align-top" style="margin-right:20px;" alt="ADC" title="Antietam Distance Company">
<!--                <span class="nav-title-span">Antietam Distance Company</span>//-->
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarsExample02">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<%= about_path %>">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<%= members_path %>">Members</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<%= events_path %>">Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<%= documents_path %>">Documents</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
					<li class="nav-item">
                        <% if user_signed_in? %>
                            <%= link_to("#{current_user.first_name} #{current_user.last_name}", edit_user_registration_path, { class: "navlink", style: "text-decoration:none;color:#9D9D9D" }) %> |
                            <%= link_to('Logout', destroy_user_session_path, { :method => :delete, style: "text-decoration:none;color:#9D9D9D" }) %>
                        <% else %>
                            <%= link_to('Login', new_user_session_path, { class: "navlink", style:"text-decoration:none;color:#9D9D9D;" })  %>
                        <% end %>
					</li>
				</ul>

            </div>
        </nav>

        <div id="main_wrapper" class="container">
            <%= yield %>
           <!-- <p class="alert alert-primary"><%#= notice %></p>
            <p class="alert alert-danger"><%#= alert %></p>-->
        </div>
<footer class="footer">
<div class="container"> 
<nav class="navbar fixed-bottom navbar-expand navbar-dark bg-dark" >
<ul class="navbar-nav"> 
  <li class="nav-item">
    <a title="Strava Club Page" class="nav-link strava" href="https://www.strava.com/clubs/antietamCO" target="_blank"></a>
  </li>
  <li class="nav-item">
    <a title="Club Twitter" class="nav-link twitter" href="https://twitter.com/AdcRuns" target="_blank"></a>
  </li>
</ul>
</nav>
</div>
</footer>
    </body>
</html>