config/routes.rb
Rails.application.routes.draw do
mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  resources :documents
  resources :events
  resources :members
    devise_for :users, :controllers => { registrations: 'registrations' }

    get 'pages/index'
	get 'about' => 'pages#about'

	root 'pages#index'

	match "*path", to: redirect('/'), via: :all

end

app/models/member.rb
class Member < ApplicationRecord
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  require 'stravapi'

  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
    @strava_members = Stravapi.getMemberList()
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :email, :school, :age)
    end
end

app/views/members/_form.html.erb
<%= form_with(model: member, local: true, html: { class: "rails_form" }) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, { id: :member_first_name, class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, { id: :member_last_name, class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, { id: :member_email, class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= form.label :school %>
    <%= form.text_field :school, { id: :member_school, class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= form.label :age %>
    <%= form.number_field :age, { id: :member_age, class: "form-control" } %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", { class: "btn btn-dark", onclick: "return checkScheduleForm();" } %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h3>Editing Member</h3>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Members</h3>

<% cspan = 1 %>
<% if user_signed_in? %>
    <% cspan = 3 %>
<% end %>
<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Member Type</th>
<!--      <th>Email</th>
      <th>School</th>
      <th>Age</th>
      <th colspan="<%= cspan %>"></th>-->
    </tr>
  </thead>

  <tbody>
    <%# @members.each do |member| %>
    <% @strava_members.each do |member| %>
      <tr>
        <td><%= member['firstname'] %></td>
        <td><%= member['lastname'] %></td>
        <td><%= member['membership'] %></td>
<!--        <td><%#= member.first_name %></td>
        <td><%#= member.last_name %></td>
        <td><%#= member.email %></td>
        <td><%#= member.school %></td>
        <td><%#= member.age %></td>
        <td><%#= link_to 'Show', member %></td>
        <%# if user_signed_in? %>
        <td><%#= link_to 'Edit', edit_member_path(member) %></td>
        <td><%#= link_to 'Delete', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%# end %>
-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Member', new_member_path %>
<% end %>

app/views/members/new.html.erb
<h3>New Member</h3>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path, { style: "" } %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>School:</strong>
  <%= @member.school %>
</p>

<p>
  <strong>Age:</strong>
  <%= @member.age %>
</p>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_member_path(@member) %> |
<% end %>
<%= link_to 'Back', members_path %>